In [4]:
import pandas as pd
import numpy as np

In [5]:
raw1= pd.read_excel("raw_night_1854_1855.xlsx")

In [22]:
raw1.head()

,Month,Avg Army Size,Disease Deaths,Wounds,Other Causes
0,Apr 1854,8571,1,0,5
1,May 1854,23333,12,0,9
2,Jun 1854,28333,11,0,6
3,Jul 1854,28722,359,0,23
4,Aug 1854,30246,828,1,30


In [23]:
raw2 = raw1["Month"].str.split(" ", expand = True).rename(columns = {0: "Months",
                                                       1: "Year"})
raw2.head()

,Months,Year
0,Apr,1854
1,May,1854
2,Jun,1854
3,Jul,1854
4,Aug,1854


In [24]:
raw = pd.concat([raw1, raw2], axis =1 )
raw.head()

,Month,Avg Army Size,Disease Deaths,Wounds,Other Causes,Months,Year
0,Apr 1854,8571,1,0,5,Apr,1854
1,May 1854,23333,12,0,9,May,1854
2,Jun 1854,28333,11,0,6,Jun,1854
3,Jul 1854,28722,359,0,23,Jul,1854
4,Aug 1854,30246,828,1,30,Aug,1854


In [9]:
Raw = (raw
         .melt(["Month", "Avg Army Size","Months","Year"], 
              var_name = "Causes of Deaths", 
              value_name = " Death Count")) 
Raw.head()

,Month,Avg Army Size,Months,Year,Causes of Deaths,Death Count
0,Apr 1854,8571,Apr,1854,Disease Deaths,1
1,May 1854,23333,May,1854,Disease Deaths,12
2,Jun 1854,28333,Jun,1854,Disease Deaths,11
3,Jul 1854,28722,Jul,1854,Disease Deaths,359
4,Aug 1854,30246,Aug,1854,Disease Deaths,828


In [10]:
Raw["Causes of Deaths"]=Raw["Causes of Deaths"].replace("Disease Deaths","Diseases")
Raw.head()

,Month,Avg Army Size,Months,Year,Causes of Deaths,Death Count
0,Apr 1854,8571,Apr,1854,Diseases,1
1,May 1854,23333,May,1854,Diseases,12
2,Jun 1854,28333,Jun,1854,Diseases,11
3,Jul 1854,28722,Jul,1854,Diseases,359
4,Aug 1854,30246,Aug,1854,Diseases,828


In [11]:
import janitor
from lets_plot import *
LetsPlot.setup_html()

In [12]:
Raw["Sq_Death Count"] = np.sqrt(Raw[ " Death Count"])
Raw.head(5)

,Month,Avg Army Size,Months,Year,Causes of Deaths,Death Count,Sq_Death Count
0,Apr 1854,8571,Apr,1854,Diseases,1,1.000000
1,May 1854,23333,May,1854,Diseases,12,3.464102
2,Jun 1854,28333,Jun,1854,Diseases,11,3.316625
3,Jul 1854,28722,Jul,1854,Diseases,359,18.947295
4,Aug 1854,30246,Aug,1854,Diseases,828,28.774989


In [13]:
Raw["Months"] = pd.Categorical(Raw["Months"],
              categories = ["Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb",  "Mar", "Apr", "May", "Jun"],
              ordered = True)

In [14]:
cause_order = ['Wounds', 'Other Causes', 'Diseases']
Raw["Causes of Deaths"] = pd.Categorical(Raw['Causes of Deaths'], categories=cause_order, ordered=True)

In [97]:
p1 = (ggplot(Raw, aes("Months", "Sq_Death Count", fill = "Causes of Deaths"))
+ geom_bar(stat='identity', alpha = 0.6)
+ scale_fill_manual(values = ["#fb9a99", "grey30", "skyblue"])
#+ coord_equal(ratio = 1) 
+ coord_polar()
+ labs(fill = "Nature of Death",
      subtitle = "APRIL 1854 TO MARCH 1855 ") 
+ theme(axis_title_y = element_blank(),
        axis_title_x = element_blank(),
        axis_text_y = element_blank(),
        axis_ticks = element_blank(),
        plot_subtitle = element_text(hjust = 0.5),
        panel_grid = element_blank(),
        panel_border = element_blank(),
         legend_position = "bottom")
+  ggsize(900, 550))

p1

In [98]:
raw_2=pd.read_excel("raw_night_1855_1856.xlsx")

In [99]:
raw_2.head()

,Month,Avg Army Size,Disease Deaths,Wounds,Other Causes
0,Apr 1855,32393,477,48,57
1,May 1855,35693,508,32,37
2,Jun 1855,40253,802,31,31
3,Jul 1855,35786,382,30,33
4,Aug 1855,51074,483,41,55


In [71]:
raw_3 =raw_2["Month"].str.split(" ", expand = True).rename(columns = {0: "Months",
                                                       1: "Year"})
raw_3.head()

,Months,Year
0,Apr,1855
1,May,1855
2,Jun,1855
3,Jul,1855
4,Aug,1855


In [72]:
Raw2=pd.concat([raw_2,raw_3],axis=1)
Raw2.head()

,Month,Avg Army Size,Disease Deaths,Wounds,Other Causes,Months,Year
0,Apr 1855,32393,477,48,57,Apr,1855
1,May 1855,35693,508,32,37,May,1855
2,Jun 1855,40253,802,31,31,Jun,1855
3,Jul 1855,35786,382,30,33,Jul,1855
4,Aug 1855,51074,483,41,55,Aug,1855


In [73]:
Raw_2= (Raw2
         .melt(["Month", "Avg Army Size","Months","Year"], 
              var_name = "Causes of Deaths", 
              value_name = " Death Count")) 
Raw_2.head()

,Month,Avg Army Size,Months,Year,Causes of Deaths,Death Count
0,Apr 1855,32393,Apr,1855,Disease Deaths,477
1,May 1855,35693,May,1855,Disease Deaths,508
2,Jun 1855,40253,Jun,1855,Disease Deaths,802
3,Jul 1855,35786,Jul,1855,Disease Deaths,382
4,Aug 1855,51074,Aug,1855,Disease Deaths,483


In [94]:
#Raw_2["Causes of Deaths"]=Raw_2["Causes of Deaths"].replace("Disease Deaths","Diseases")
#Raw_2.head()

In [101]:
Raw_2["Sq_Death Count"] = np.sqrt(Raw_2[ " Death Count"])
Raw_2

,Month,Avg Army Size,Months,Year,Causes of Deaths,Death Count,Sq_Death Count
0,Apr 1855,32393,Apr,1855,Diseases,477,21.840330
1,May 1855,35693,May,1855,Diseases,508,22.538855
2,Jun 1855,40253,Jun,1855,Diseases,802,28.319605
3,Jul 1855,35786,Jul,1855,Diseases,382,19.544820
4,Aug 1855,51074,Aug,1855,Diseases,483,21.977261
5,Sep 1855,52280,Sep,1855,Diseases,189,13.747727
6,Oct 1855,53321,Oct,1855,Diseases,128,11.313708
7,Nov 1855,45679,Nov,1855,Diseases,178,13.341664
8,Dec 1855,36241,Dec,1855,Diseases,91,9.539392
9,Jan 1856,34292,Jan,1856,Diseases,42,6.480741


In [76]:
Raw_2["Months"] = pd.Categorical(Raw_2["Months"],
              categories = ["Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "Jan", "Feb",  "Mar", "Apr", "May", "Jun"],
              ordered = True)

In [77]:
import janitor
from lets_plot import *
LetsPlot.setup_html()

In [78]:

Raw_2["Causes of Deaths"] = pd.Categorical(Raw_2["Causes of Deaths"],
              categories = ["Wounds", "Other Causes", "Diseases"],
              ordered = True)

In [81]:
p2 = (ggplot(Raw_2, aes("Months", "Sq_Death Count", fill = "Causes of Deaths"))
+ geom_bar(stat='identity', alpha = 0.6, show_legend = False)
+ scale_fill_manual(values = ["#fb9a99", "grey30", "skyblue"]) 
+ coord_polar()
+ labs(fill = "Causes of Deaths",
      subtitle = "APRIL 1855 TO MARCH 1856") 
+ theme(axis_title_y = element_blank(),
        axis_title_x = element_blank(),
        axis_text_y = element_blank(),
        axis_ticks = element_blank(),
        plot_subtitle = element_text(hjust = 0.5),
        panel_grid = element_blank(),
        panel_border = element_blank())
+  ggsize(900, 550))

p2

In [100]:
gggrid([p2, p1], ncol = 2) + ggtitle("Diagram Of The Causes Of Mortality In The Army In The East")

**Interpretation of Result**:The nature of death in the army were caused by diseases rather than wounds or other causes. In the period April 1854–March 1855, disease-related deaths were extremely high. However, in April 1855–March 1856, there was a sharp reduction in deaths from diseases, indicating improved sanitary conditions. Overall, the analysis highlights how better healthcare measures greatly reduced mortality.